#!/data/data/com.termux/files/usr/bin/bash


# SPDX-License-Identifier: GPL-3.0-or-later
#
# Original project: termux-style
# Authors: Aditya Shakya, Fredrik Fornwall
#
# Modified by: Alia Ether
# Realme Edition
# 2026



## Mi uninstall script
## Author : Frontend & LED (𝙰𝚕𝚒𝚊 𝙴𝚝𝚑𝚎𝚛 𖤍)

## ANSI Colors (FG & BG)
RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')" BLACKBG="$(printf '\033[40m')"
DEFAULT_FG="$(printf '\033[39m')"  DEFAULT_BG="$(printf '\033[49m')"

## Directories
PREFIX='/data/data/com.termux/files/usr'

## Banner
banner () {
clear
echo "
${BLUE}

⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⠀⠀⣰⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⡀⠀⢀⠒⠑⣴⣦⣾⣧⣤⢀⡤⠀⠀⠀⡀⠀⠀⠀
⠀⠀⠀⠀⢀⠀⢀⡘⠉⠁⣰⣾⣿⣿⣿⣿⣿⣿⣷⢀⡤⠊⠀⠀⠀⠀
⠀⠀⠀⠀⠀⢱⠊⡄⠒⠾⣿⣿⣿⣿⣿⣿⠿⠛⢹⣿⣯⣤⠤⠄⠀⠀
⠀⠀⠀⠒⢦⠂⠀⣇⠀⠸⠟⢈⣿⣿⡁⠺⠗⠀⣸⣿⣿⣃⠀⠀⠀⠀
⠀⠀⠀⠀⢘⢀⣼⠻⢷⣶⣶⣿⣿⣿⣿⣶⣶⣾⠟⣻⣿⡯⠁⠀⠀⠀
⠀⠀⠀⠉⠱⢾⣿⡀⠀⠈⠉⠙⠛⠛⠛⠉⠉⠀⢀⣿⣿⠿⠛⠒⠀⠀
⠀⠀⠀⠀⠔⢛⣿⣷⡈⠒⠀⠀⠀⠔⠁⠊⠒⢈⣾⣿⡏⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠜⠛⠿⣿⣶⣤⣀⣀⣀⣀⣤⣶⣿⠿⣿⠉⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⡸⠛⢉⡿⠻⠟⣿⢿⡟⣏⠁⠀⠘⠄⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⡜⠀⠀⠀⠁⠀⠃⠘⡀⠀⠀

███████╗██╗
██╔════╝██║
█████╗  ██║
██╔══╝  ██║
██║     ███████╗
╚═╝     ╚══════╝

${BLUE}[${RED}*${BLUE}] ${ORANGE}Mi Uninstaller ${RED}//${ORANGE} Frontend & LED
"
}

## Signals
trap 'echo -e "\n${RED}Interrupted"; reset_color; exit 0' SIGINT
trap 'echo -e "\n${RED}Terminated"; reset_color; exit 0' SIGTERM

## Reset terminal colors
reset_color() {
tput sgr0
tput op
}

## Uninstall Mi
uninstall_mi () {

banner

if [[ (-L $PREFIX/bin/Mi) && (-d $PREFIX/share/Mi) ]]; then

echo
echo "    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Uninstalling Mi..."
echo "    ${BLUE}[${RED}*${BLUE}] ${RED}Removing files from $PREFIX/share"

rm -r $PREFIX/share/Mi $PREFIX/bin/Mi

if [[ (! -L $PREFIX/bin/Mi) && (! -d $PREFIX/share/Mi) ]]; then
echo
echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Uninstalled Successfully."
reset_color
exit 0
else
echo "    ${BLUE}[${RED}!${BLUE}] ${RED}Error Occured."
reset_color
exit 1
fi

else
echo
echo "    ${BLUE}[${RED}!${BLUE}] ${MAGENTA}Mi ${GREEN}is not installed."
reset_color
exit 0
fi
}

uninstall_mi
